apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    env: test
spec:
  containers:
  - name: mycontainer
    image: myimage
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "test"
    operator: "Exists"
    effect: "NoSchedule"
